### ISSUE TITLE
Add details in the documentation about the options of the program

### ISSUE THREAD

**Issue by phupe** [bioinfo-pf-curie/mpiSORT#14]
Add details in the documentation about the options of the program: detail what are the purposes au -q and -n options.

**Comment by phupe** [comment]
@fredjarlier : can you detail what are the purposes au -q and -n options in a comment of this issue?

**Comment by fredjarlier** [comment]
-q is for filtering reads by quality. Reads quality under the threshold are ignored in the sorting results.
-n is for sorting by read's name (but it is not commonly used).
