### ISSUE TITLE
Add singularity recipe

### ISSUE THREAD

**Issue by phupe** [bioinfo-pf-curie/mpiSORT#2]
Provide a singularity recipe with the mpiSORT executable.

**Comment by phupe** [comment]
To be done: delete the `git checkout devel` in the recipe

**Comment by fredjarlier** [comment]
I don't know if it is a good idea to mention singularity. Because even with Singularity MPI must be installed on the server otherwise Singularity cannot access the drivers.

We can mention it anyway...

**Comment by phupe** [comment]
delete the `git checkout devel `in the recipe: done
