### ISSUE TITLE
Write a grid explorer

### ISSUE THREAD

**Issue by fredjarlier** [bioinfo-pf-curie/mpiSORT#40]
Propose a simple script to explore the cluster architecture.

The idea is to get a overview of the cluster topology at partition, node, network, etc... level in order to help users building the right  command line.

**Comment by phupe** [comment]
the script `grid_explorer.sh` provides very interesting information. As the hardware memory for each node is not dispalyed, I suggest to add the information retrived by:

`sinfo -o "%20N  %10c  %m  %25f  %10G "`

**Comment by phupe** [comment]
@fredjarlier , I added a python script to compoute the informatic resources required for mpiSORT depending on the size of the FASTQ file. 

Print help:
`python informaticResources.py -h`

Example:
`python informaticResources.py -c 40 -m 133 -s 1300`


TODO:
* [x] check the script
* [x] modify the doc to show an example using this script

**Comment by phupe** [comment]
the script `grid_explorer.sh` has been renamed into `getSlurmNodesInfo.sh`.

**Comment by fredjarlier** [comment]
Done in release-1.4
