### ISSUE TITLE
Add an option to write an entire SAM in output

### ISSUE THREAD

**Issue by fredjarlier** [bioinfo-pf-curie/mpiSORT#52]

**Comment by fredjarlier** [comment]
add an option -m to merge output in a single sam.
it only works for sam format.

example command line:
mpirun -n 8 $MPISORT $SAM $OUTPUT_FOLDER -p -s -m -q 0

the output file is derived from input sam like this
if sam input is ERR19.sam
then sam output is ERR19_sorted.sam

**Comment by fredjarlier** [comment]
to do
1) merge compressed sam file.
2) update documentation

**Comment by tahashmi** [comment]
Can we do it for `bam` as well?

**Comment by fredjarlier** [comment]
yes to produce only one bam use options: -b -m
