### ISSUE TITLE
Problem with bam construction

### ISSUE THREAD

**Issue by fredjarlier** [bioinfo-pf-curie/mpiSORT#64]

**Comment by fredjarlier** [comment]
follow up on issue #45

**Comment by fredjarlier** [comment]
@tahashmi

**Comment by fredjarlier** [comment]
Hi @tahashmi

I don't reproduce your issue, I sort my HG002_HiSeq30x.sam of 273g and produce a 61g of bam and no warning.
Could you try aligning it with mpiBWA or BWA please?

[test_30X_mpi_sort_722615.txt](https://github.com/bioinfo-pf-curie/mpiSORT/files/7989106/test_30X_mpi_sort_722615.txt)

**Comment by tahashmi** [comment]
Thanks for the updates. I think I have some issues on HPC gpfs. Yesterday, I ran again and it created 68GB BAM. DeepVariant has some issues as well on HPC. But I have created index file with samtools and calling variants with Clair3 is also fine.

**Comment by fredjarlier** [comment]
ok good, it should work for deepvariant also.
I think we can close the case for now and say the next step for this feature is to generate the index on the fly with mpiSORT.

**Comment by tahashmi** [comment]
Sure. :-)
